import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CircleCheck } from 'lucide-react'
import FloatingNavigation from '@/components/FloatingNavigation'
import PublicFooter from '@/components/PublicFooter'
import PublicHeader from '@/components/PublicHeader'
import { PACCHETTI } from '@/lib/pacchetti'
import { SITE_URL } from '@/lib/site-config'
import base from '../content-page.module.css'
import styles from './pacchetti.module.css'

const title='Pacchetti Social, Siti Web ed E-commerce per PMI | SWA'
const description='Confronta Presenza, Crescita e Web & Commerce: gestione social da 390 € e siti o e-commerce da 19,90 €/mese. Servizi e costi in chiaro.'
const wa=`https://wa.me/393477196603?text=${encodeURIComponent('Ciao! Vorrei capire quale pacchetto Social Automation è adatto alla mia azienda.')}`
export const metadata:Metadata={title,description,alternates:{canonical:`${SITE_URL}/pacchetti`},openGraph:{title,description,url:`${SITE_URL}/pacchetti`},twitter:{title,description}}

const faq=[
  {q:'I prezzi includono l’IVA?',a:'No. I prezzi indicati sono mensili e IVA esclusa.'},
  {q:'Il setup iniziale ha un costo?',a:'No. Nei pacchetti Presenza e Crescita il setup è incluso.'},
  {q:'Il budget ADS è compreso nel piano Crescita?',a:'La gestione di una campagna è inclusa; il budget versato alla piattaforma pubblicitaria è separato e resta sotto il controllo del cliente.'},
  {q:'Sito web ed e-commerce sono inclusi nei pacchetti social?',a:'No. Web & Commerce è un pacchetto separato, combinabile con Presenza o Crescita. Il canone tecnologico parte da 19,90 € al mese e dopo 12 mesi il sito diventa tuo; progettazione, funzioni ed eventuali servizi esterni vengono definiti prima dell’avvio.'},
  {q:'Posso richiedere una configurazione diversa?',a:'Sì. Più brand, più canali, e-commerce, volumi elevati, video, automazioni e integrazioni vengono quotati dopo una valutazione iniziale.'},
]

export default function PacchettiPage(){
  const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'WebPage',url:`${SITE_URL}/pacchetti`,name:title,description,inLanguage:'it-IT'},{'@type':'OfferCatalog',name:'Pacchetti Social Automation',itemListElement:[...PACCHETTI.map(p=>({'@type':'Offer',name:p.nome,price:p.prezzo.replace(/[^0-9]/g,''),priceCurrency:'EUR',url:`${SITE_URL}/register?piano=${p.slug}`,description:p.sottotitolo})),{'@type':'Offer',name:'Web & Commerce',price:'19.90',priceCurrency:'EUR',url:`${SITE_URL}/servizi/siti-e-commerce`,description:'Pacchetto separato per siti web ed e-commerce mobile-first. Dopo 12 mesi di canone il sito diventa di proprietà del cliente.'}]},{'@type':'FAQPage',mainEntity:faq.map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE_URL},{'@type':'ListItem',position:2,name:'Pacchetti',item:`${SITE_URL}/pacchetti`}]}]}
  return <main id="main-content" className={base.page}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,'\\u003c')}}/>
    <a className={base.skipLink} href="#main-content">Vai al contenuto</a><PublicHeader ctaHref={wa} ctaLabel="Scegli il piano"/>
    <section className={base.hero}><nav className={base.breadcrumbs}><Link href="/">Home</Link><span>/</span><span>Pacchetti</span></nav><p className={base.eyebrow}>Soluzioni mensili trasparenti</p><h1>Tre pacchetti chiari. Una soluzione su misura quando serve.</h1><p className={base.lead}>Presenza e Crescita gestiscono social e visibilità. Web & Commerce costruisce il punto di conversione digitale. Ogni perimetro, costo e responsabilità viene definito prima dell’avvio.</p><div className={base.heroActions}><a href="#confronto" className={base.primary}>Confronta i pacchetti <ArrowRight size={17}/></a><a href={wa} target="_blank" rel="noopener noreferrer" className={base.secondary}>Aiutami a scegliere</a></div></section>
    <section id="confronto" className={styles.pricing}><div className={base.sectionHeading}><p className={base.eyebrow}>Social o presenza web</p><h2>Scegli in base al risultato, non al numero di funzioni.</h2><p>Due pacchetti gestiscono comunicazione e crescita. Il terzo realizza siti ed e-commerce mobile-first, anche come progetto autonomo.</p></div><div className={styles.grid}>{PACCHETTI.map(p=><article key={p.slug} className={`${styles.card} ${p.consigliato?styles.featured:''}`}><div className={styles.top}><div><span className={styles.audience}>{p.eyebrow}</span><h2>{p.nome}</h2></div>{p.consigliato&&<span className={styles.badge}>Più scelto</span>}</div><p className={styles.result}>{p.risultato}</p><p className={styles.price}><strong>{p.prezzo}</strong><span>/mese</span></p><p className={styles.setup}>{p.setup}</p><p className={styles.description}>{p.sottotitolo}</p><div className={styles.fit}><strong>È adatto a te se</strong><p>{p.idealePer}</p></div>{p.includeDa&&<p className={styles.includes}>Include tutto di {p.includeDa}, più:</p>}<p className={styles.listLabel}>Nel canone trovi</p><ul>{p.features.map(f=><li key={f}><CircleCheck size={15}/>{f}</li>)}</ul><Link href={`/register?piano=${p.slug}`}>{p.cta}<ArrowRight size={16}/></Link><p className={styles.note}>Setup incluso · IVA esclusa · rinnovo mensile</p></article>)}<article className={`${styles.card} ${styles.webCard}`}><div className={styles.top}><div><span className={styles.audience}>Professionisti, PMI e negozi</span><h2>Web & Commerce</h2></div><span className={styles.badge}>Sito tuo</span></div><p className={styles.result}>Un sito credibile che trasforma visite in contatti o vendite.</p><p className={styles.price}><span>da</span><strong>€19,90</strong><span>/mese</span></p><p className={styles.setup}>Dopo 12 mesi di canone, il sito è tuo</p><p className={styles.description}>Canone tecnologico di partenza. Progettazione, configurazione e funzioni vengono quotate prima dell’avvio.</p><div className={styles.fit}><strong>È adatto a te se</strong><p>Ti serve una landing, un sito aziendale o un e-commerce mobile-first collegato a campagne, contenuti e analytics.</p></div><p className={styles.listLabel}>Nel progetto trovi</p><ul>{['Architettura, UX e design responsive','Landing page, sito o catalogo e-commerce','SEO tecnica, sitemap e dati strutturati','Moduli, checkout, analytics e integrazioni','Collegamento a social e campagne','Proprietà del sito dopo 12 mesi'].map(f=><li key={f}><CircleCheck size={15}/>{f}</li>)}</ul><Link href="/servizi/siti-e-commerce">Configura Web & Commerce <ArrowRight size={16}/></Link><p className={styles.note}>IVA esclusa · dominio e servizi esterni separati</p></article></div>
      <div className={styles.comparison}><table><caption>Confronto rapido</caption><thead><tr><th>Servizio</th><th>Presenza</th><th>Crescita</th><th>Web & Commerce</th></tr></thead><tbody><tr><td>Canali social</td><td>2</td><td>3</td><td>—</td></tr><tr><td>Contenuti mensili</td><td>16</td><td>24</td><td>—</td></tr><tr><td>Reel, Story o Short</td><td>4</td><td>6</td><td>—</td></tr><tr><td>Articolo SEO + GEO</td><td>—</td><td>1/mese</td><td>SEO tecnica</td></tr><tr><td>Gestione campagna ADS</td><td>—</td><td>1</td><td>Integrazione tracking</td></tr><tr><td>Sito / e-commerce</td><td>—</td><td>—</td><td>Da 19,90 €/mese</td></tr><tr><td>Proprietà dopo 12 mesi</td><td>—</td><td>—</td><td>Sì</td></tr><tr><td>Call strategica</td><td>30 min</td><td>45 min</td><td>Brief di progetto</td></tr></tbody></table></div>
    </section>
    <section className={styles.custom}><div><span>Configurazione personalizzata</span><h2>Più brand, e-commerce, volumi elevati o integrazioni.</h2><p>Costruiamo un perimetro dedicato quando i tre pacchetti standard non rappresentano il processo reale dell’azienda.</p></div><a href={wa} target="_blank" rel="noopener noreferrer">Progettiamo la soluzione <ArrowRight size={17}/></a></section>
    <section className={`${base.section} ${base.faqLayout}`}><div className={base.sectionHeading}><p className={base.eyebrow}>FAQ pacchetti</p><h2>Costi e condizioni in chiaro.</h2></div><div className={base.faqList}>{faq.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section>
    <section className={base.finalCta}><div><p className={base.eyebrow}>Prima di scegliere</p><h2>Valutiamo insieme canali e obiettivi.</h2><p>Ti indichiamo il piano sostenibile o il perimetro personalizzato necessario.</p></div><a href={wa} target="_blank" rel="noopener noreferrer">Richiedi una valutazione <ArrowRight size={17}/></a></section><PublicFooter/><FloatingNavigation/>
  </main>
}
