'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

interface ContentItem {
  id: string;
  content_type: string;
  topic: string;
  copy_hook: string;
  copy_body: string;
  copy_cta: string;
  hashtags: string[];
  suggested_sound?: string;
  generated_by: string;
  created_at: string;
}

export function AIContentApproval({ clienteId }: { clienteId: string }) {
  const [contents, setContents] = useState<ContentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [publishing, setPublishing] = useState<string | null>(null);

  // Fetch pending content
  useEffect(() => {
    const fetchContent = async () => {
      try {
        const res = await fetch(`/api/ai-automation/content-queue?clienteId=${clienteId}`);
        const data = await res.json();
        setContents(data.data || []);
      } catch (error) {
        console.error('Error fetching content:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchContent();
  }, [clienteId]);

  const handleApprove = async (contentId: string) => {
    setPublishing(contentId);
    try {
      // 1. Approve in queue
      const approveRes = await fetch(`/api/ai-automation/content-queue`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentId,
          status: 'APPROVED',
        }),
      });

      if (!approveRes.ok) {
        throw new Error('Failed to approve');
      }

      const approved = await approveRes.json();
      const content = approved.data;

      // 2. Publish to Blotato
      const publishRes = await fetch(`/api/ai-automation/publish`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentId,
          platform: 'Instagram', // TODO: Make dynamic
          blotatoApiKey: process.env.NEXT_PUBLIC_BLOTATO_API_KEY,
          copyHook: content.copy_hook,
          copyBody: content.copy_body,
          copyCta: content.copy_cta,
          hashtags: JSON.parse(content.hashtags || '[]'),
        }),
      });

      if (!publishRes.ok) {
        throw new Error('Failed to publish');
      }

      // Remove from pending
      setContents(contents.filter((c) => c.id !== contentId));
      alert('✅ Content published!');
    } catch (error) {
      alert(`❌ Error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setPublishing(null);
    }
  };

  const handleReject = async (contentId: string) => {
    try {
      const res = await fetch(`/api/ai-automation/content-queue`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contentId,
          status: 'REJECTED',
        }),
      });

      if (!res.ok) throw new Error('Failed to reject');

      setContents(contents.filter((c) => c.id !== contentId));
      alert('❌ Content rejected');
    } catch (error) {
      alert(`Error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  };

  if (loading) return <div>Loading content...</div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">📝 AI-Generated Content</h2>
        <span className="text-sm bg-blue-100 px-3 py-1 rounded">
          {contents.length} pending
        </span>
      </div>

      {contents.length === 0 ? (
        <Card>
          <CardContent className="pt-6 text-center text-gray-500">
            No pending content. Check back later!
          </CardContent>
        </Card>
      ) : (
        contents.map((content) => (
          <Card key={content.id} className="border-l-4 border-l-blue-500">
            <CardHeader>
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle className="text-lg">
                    {content.content_type} — {content.topic}
                  </CardTitle>
                  <CardDescription>
                    Generated by {content.generated_by} • {new Date(content.created_at).toLocaleString()}
                  </CardDescription>
                </div>
              </div>
            </CardHeader>

            <CardContent className="space-y-4">
              {/* Hook */}
              <div className="bg-yellow-50 p-3 rounded border border-yellow-200">
                <p className="text-sm font-semibold text-yellow-900">🎯 Hook (First 2s)</p>
                <p className="text-yellow-900 mt-1">{content.copy_hook}</p>
              </div>

              {/* Body */}
              <div className="bg-blue-50 p-3 rounded border border-blue-200">
                <p className="text-sm font-semibold text-blue-900">📝 Body</p>
                <p className="text-blue-900 mt-1 whitespace-pre-wrap">{content.copy_body}</p>
              </div>

              {/* CTA */}
              <div className="bg-green-50 p-3 rounded border border-green-200">
                <p className="text-sm font-semibold text-green-900">✨ Call-to-Action</p>
                <p className="text-green-900 mt-1">{content.copy_cta}</p>
              </div>

              {/* Hashtags */}
              <div>
                <p className="text-sm font-semibold mb-2">🏷️ Hashtags</p>
                <div className="flex flex-wrap gap-2">
                  {JSON.parse(
                    typeof content.hashtags === 'string' ? content.hashtags : '[]'
                  ).map((tag: string) => (
                    <span key={tag} className="bg-gray-200 px-2 py-1 rounded text-sm">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>

              {/* Suggested Sound (for reels) */}
              {content.suggested_sound && (
                <div className="bg-purple-50 p-3 rounded border border-purple-200">
                  <p className="text-sm font-semibold text-purple-900">🎵 Suggested Sound</p>
                  <p className="text-purple-900 mt-1">{content.suggested_sound}</p>
                </div>
              )}

              {/* Actions */}
              <div className="flex gap-2 pt-4 border-t">
                <Button
                  onClick={() => handleApprove(content.id)}
                  disabled={publishing === content.id}
                  className="flex-1 bg-green-600 hover:bg-green-700"
                >
                  {publishing === content.id ? '⏳ Publishing...' : '✅ Approve & Publish'}
                </Button>
                <Button
                  onClick={() => handleReject(content.id)}
                  variant="outline"
                  className="flex-1"
                >
                  ❌ Reject
                </Button>
              </div>
            </CardContent>
          </Card>
        ))
      )}
    </div>
  );
}
