import type { Metadata } from 'next'
import LegalShell from '@/components/LegalShell'
import LegalPrevalenza from '@/components/LegalPrevalenza'
import { anteprimaOg } from '@/lib/anteprima'
import { TITOLARE } from '@/lib/legal-config'
import { SITE_URL } from '@/lib/site-config'
import styles from '@/components/legal.module.css'

const META_TITLE = 'Accessibility statement — Social Web Automation'
const META_DESCRIPTION =
  'The accessibility level of the Social Web Automation website, what has been verified, which limits remain and how to report a barrier that stops you using the site.'

export const metadata: Metadata = {
  title: META_TITLE,
  description: META_DESCRIPTION,
  alternates: {
    canonical: `${SITE_URL}/en/accessibility`,
    languages: {
      'it-IT': `${SITE_URL}/accessibilita`,
      en: `${SITE_URL}/en/accessibility`,
      'x-default': `${SITE_URL}/accessibilita`,
    },
  },
  openGraph: { title: META_TITLE, description: META_DESCRIPTION, url: `${SITE_URL}/en/accessibility`, images: anteprimaOg('/en/accessibility'), type: 'website', locale: 'en_US' },
  robots: { index: true, follow: true },
}

export default function AccessibilityPage() {
  return (
    <LegalShell
      eyebrow="Accessibility"
      title="Accessibility statement"
      currentPath="/en/accessibility"
      locale="en"
      altraLinguaHref="/accessibilita"
    >
      <LegalPrevalenza href="/accessibilita" />

      <p>
        {TITOLARE.brand} is committed to making its website usable by anyone, including people who browse
        with a screen reader, by keyboard only, with enlarged text or with high contrast. This page states
        where we are, what has been verified and what has not.
      </p>

      <h2>1. Reference standard</h2>
      <p>
        The reference is the <strong>Web Content Accessibility Guidelines (WCAG) 2.1, level AA</strong>, cited
        by the European standard EN 301 549 and, in Italy, by Law 4/2004 as amended by Legislative Decree
        82/2022 implementing the European Accessibility Act.
      </p>

      <h2>2. Conformance status</h2>
      <p>
        We declare <strong>partial conformance</strong> with WCAG 2.1 AA. “Partial” is not a convenient
        formula: it means the criteria listed under point 3 have been verified and are met, while those under
        point 4 have not yet been verified with automated tools and complete manual testing.
      </p>

      <h2>3. What has been verified</h2>
      <ul>
        <li><strong>Alternative text</strong>: every informative image has a description; decorative ones are marked as such.</li>
        <li><strong>Heading structure</strong>: one <code>h1</code> per page and a hierarchy with no skipped levels.</li>
        <li><strong>Form labels</strong>: every field has an associated label or an <code>aria-label</code>.</li>
        <li><strong>Link text</strong>: no “click here” or “read more” without context.</li>
        <li><strong>Page language</strong>: declared and correct on the English pages too, where it is set before the page is first painted.</li>
        <li><strong>Zoom and mobile devices</strong>: content stays readable and usable up to 200% zoom and on narrow screens.</li>
        <li><strong>Skip to content</strong>: every page opens with a keyboard-reachable “Skip to content” link.</li>
        <li><strong>Light and dark themes</strong>: both designed, not produced by automatic inversion.</li>
      </ul>

      <h2>4. Known limitations</h2>
      <p>We write them down because knowing where the site is weak is more useful than a generic statement.</p>
      <ul>
        <li><strong>Colour contrast</strong>: verified on the main surfaces, not yet on every combination of every component in both themes.</li>
        <li><strong>Keyboard path</strong>: navigable, but tab order and focus visibility have not been tested page by page.</li>
        <li><strong>Screen reader testing</strong>: a full cycle with NVDA, VoiceOver or JAWS has not yet been run.</li>
        <li><strong>Attached documents</strong>: any PDFs generated by the services are not guaranteed to be accessible.</li>
        <li><strong>Third-party content</strong>: embedded social posts, where present, follow the accessibility of the platform hosting them, not ours.</li>
      </ul>

      <h2>5. How to report a barrier</h2>
      <p>
        If something stops you using the site, write to <a href={`mailto:${TITOLARE.email}`}>{TITOLARE.email}</a>{' '}
        saying which page it is and what you were trying to do. We reply within <strong>30 days</strong>. You do
        not need to know the technical name of the problem: “I cannot fill in the form with the keyboard” is a
        perfect report.
      </p>
      <p className={styles.nota}>
        If the answer does not satisfy you, you can turn to the{' '}
        <strong>Agenzia per l’Italia Digitale (AgID)</strong>, which runs the complaint mechanism provided for
        by Law 4/2004.
      </p>

      <h2>6. How we improve</h2>
      <p>
        Accessibility is checked when a page is added or a shared component changes, not once a year. The
        limitations under point 4 are on the work list: when one is closed, this page changes together with the
        site, not afterwards.
      </p>

      <h2>7. Date of this statement</h2>
      <p>
        Written on <strong>8 September 2026</strong> on the basis of an internal review of the code and the
        public pages. It was not carried out by a third-party evaluator.
      </p>
    </LegalShell>
  )
}
